# Generated by Django 5.1.1 on 2025-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passport_photo', models.ImageField(upload_to='passports/')),
                ('receipt_photo', models.ImageField(upload_to='receipts/')),
                ('is_verified', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Barcode',
        ),
        migrations.DeleteModel(
            name='Expected_info',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
