# Generated by Django 5.2 on 2025-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_busticket_delete_barcode_delete_expected_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extractedimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='extracted_images/')),
                ('extracted_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BusTicket',
        ),
    ]
