# Generated by Django 5.2 on 2025-05-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0003_extractedimage_delete_busticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passport_image', models.ImageField(upload_to='extracted_images/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
    ]
