# Generated by Django 5.2 on 2025-05-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0004_check_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check_info',
        ),
    ]
