# Generated by Django 5.2 on 2025-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0005_delete_check_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
            ],
        ),
    ]
